### ISSUE TITLE
new release 1.4.1

### ISSUE THREAD

**Issue by Tieske** [lunarmodules/say#18]
based on PR #17 a new release was tagged, and is visisble in releases tab. But wasn't uploaded to luarocks.

**Comment by Tieske** [comment]
the tag is not on the latest rockspec updated release

**Comment by Tieske** [comment]
retagged on the last commit.

not entirely sure what that does to the releases?

**Comment by alerque** [comment]
I botched some things about this release, but it doesn't help that you're messing with it at the same time. Please wait.

**Comment by Tieske** [comment]
sorry about that. Hadn't noticed. The last CI now fails on pushing because it exists on LR already.

I'll wait for now 🙏

**Comment by alerque** [comment]
I think things should be straightened out now. Sorry for the mess, definitely my mistakes while publishing combined with the catch-22 in the CI/publishing workflow.

The underlying issue is https://github.com/lunarmodules/.github/issues/4 — in this case I leaked a rockpec format 3 field into the tagged rockspec which is supposed to be compatible with older formats. It wasn't caught be CI because our test builds don't work until after tagging. To top matters off it isn't even fixable at that point because adding a rockrel bump doesn't trigger a publish even if CI passes.

I'll mess with the workflow and see if I can come up with something that doesn't leave projects in such a pickle.

**Comment by Tieske** [comment]
thx for the hard work!
